[versions]
flyway-plugin = "11.19.1"
jda = "6.2.0"
json = "20251224"
kotlin = "2.3.0"
kotlin-logging = "7.0.13"
kover = "0.9.4"
mockito-kotlin = "6.1.0"
okhttp = "5.3.2"
spring-boot = "3.5.7"
spring-dependency-management = "1.1.7"
zonky = "2.7.1"

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
json = { module = "org.json:json", version.ref = "json" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
zonky = { module = "io.zonky.test:embedded-database-spring-test", version.ref = "zonky" }

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway-plugin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
